apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suren-m/cndev-config
    targetRevision: HEAD
    path: kustomization/istio-demo
  destination:
    server: https://kubernetes.default.svc
    #namespace: istio-demo
