apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strings-app-live-demo
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomization/dev
    repoURL: 'https://github.com/suren-m/cndev-config.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
